# ID3

![img](images/1.jpg)

MP3 파일에는 음악 데이터 외에도 노래의 제목, 아티스트, 앨범, 커버이미지 등의 여러가지 정보를 포함할 수 있는데 이런 정보를 메타데이터(Metadata)라고 하며 이 메타데이터를 어떤 규칙성, 형태로 저장할꺼냐를 정해놓은게 있는데 MP3 메타데이터에서 표준으로 가장 많이 사용되는 형식이 ID3 라고 보시면 됩니다. ID3 는 서로 호환 되지 않는 v1 과 v2 버전이 있으며 이 두가지 버전은 하나의 MP3 에 동시에 존재할 수도 있습니다.

### ID3v1 [[공식링크]](https://id3.org/ID3v1)

현재 거의 사용되지 않는 ID3v1은 v1 과 v1.1 두종류의 버전이 있습니다. ID3v1 은 MP3 파일의 끝 부분에 128 바이트를 덧붙혀 메타데이터를 기록합니다. 

<table width="100%" border="1">
    <tr>
        <td width="49%" style="text-align:center">ID3v1</td>
        <td></td>
        <td width="49%" style="text-align:center">ID3v1.1</td>
    </tr>
    <tr>
        <td style="vertical-align:top">
            <table width="100%" border="0">
                <tr>
                    <td width="15%" style="text-align:center">오프셋</td>
                    <td width="15%" style="text-align:center">길이</td>
                    <td width="70%" style="text-align:center">설명</td>
                </tr>
                <tr>
                    <td style="text-align:center;">0</td>
                    <td style="text-align:center;">3</td>
                    <td style="text-align:left;padding-left:20px;">"TAG" 문자열</td>
                </tr>
                <tr>
                    <td style="text-align:center;">3</td>
                    <td style="text-align:center;">30</td>
                    <td style="text-align:left;padding-left:20px;">음악 제목 문자열</td>
                </tr>
                <tr>
                    <td style="text-align:center;">33</td>
                    <td style="text-align:center;">30</td>
                    <td style="text-align:left;padding-left:20px;">가수(아티스트) 문자열</td>
                </tr>
                <tr>
                    <td style="text-align:center;">63</td>
                    <td style="text-align:center;">30</td>
                    <td style="text-align:left;padding-left:20px;">앨범정보 문자열</td>
                </tr>
                <tr>
                    <td style="text-align:center;">93</td>
                    <td style="text-align:center;">4</td>
                    <td style="text-align:left;padding-left:20px;">발매년도 문자열</td>
                </tr>
                <tr>
                    <td style="text-align:center;">97</td>
                    <td style="text-align:center;">30</td>
                    <td style="text-align:left;padding-left:20px;">기타 문자열</td>
                </tr>
                <tr>
                    <td style="text-align:center;">127</td>
                    <td style="text-align:center;">1</td>
                    <td style="text-align:left;padding-left:20px;">장르 식별자</td>
                </tr>
            </table>
        </td>
        <td></td>
        <td>
            <table width="100%" border="0">
                <tr>
                    <td width="15%" style="text-align:center">오프셋</td>
                    <td width="15%" style="text-align:center">길이</td>
                    <td width="70%" style="text-align:center">설명</td>
                </tr>
                <tr>
                    <td style="text-align:center;">0</td>
                    <td style="text-align:center;">3</td>
                    <td style="text-align:left;padding-left:20px;">"TAG" 문자열</td>
                </tr>
                <tr>
                    <td style="text-align:center;">3</td>
                    <td style="text-align:center;">30</td>
                    <td style="text-align:left;padding-left:20px;">음악 제목 문자열</td>
                </tr>
                <tr>
                    <td style="text-align:center;">33</td>
                    <td style="text-align:center;">30</td>
                    <td style="text-align:left;padding-left:20px;">가수(아티스트) 문자열</td>
                </tr>
                <tr>
                    <td style="text-align:center;">63</td>
                    <td style="text-align:center;">30</td>
                    <td style="text-align:left;padding-left:20px;">앨범정보 문자열</td>
                </tr>
                <tr>
                    <td style="text-align:center;">93</td>
                    <td style="text-align:center;">4</td>
                    <td style="text-align:left;padding-left:20px;">발매년도 문자열</td>
                </tr>
                <tr>
                    <td style="text-align:center;">97</td>
                    <td style="text-align:center;">28</td>
                    <td style="text-align:left;padding-left:20px;">기타 문자열</td>
                </tr>
                <tr>
                    <td style="text-align:center;">125</td>
                    <td style="text-align:center;">1</td>
                    <td style="text-align:left;padding-left:20px;">바이트분리(항상 NULL)</td>
                </tr>
                <tr>
                    <td style="text-align:center;">126</td>
                    <td style="text-align:center;">1</td>
                    <td style="text-align:left;padding-left:20px;">곡 번호 바이트</td>
                </tr>
                <tr>
                    <td style="text-align:center;">127</td>
                    <td style="text-align:center;">1</td>
                    <td style="text-align:left;padding-left:20px;">장르 식별자</td>
                </tr>
            </table>
        </td>
    </tr>
</table>

ID3v1 과 v1.1 은 기본적으로 모든 문자열이 ISO-8859-1으로 인코딩 되어있습니다. 쉽게 시스템 기본 문자열을 따른다고 보시면 됩니다.

### ID3v2 [[공식링크]](https://id3.org/id3v2.3.0)

기존의 ID3v1 은 데이터가 저장될 공간이 128바이트로 한정되기 때문에 정보의 한계성과 확장이 되지 않는 단점을 갖고 있는데 이 문제를 해결하기 위해 나온것이 ID3v2 버전 이며 현재 가장 많이 사용되는 ID3 버전 입니다. ID3v2버전은 v2.2, v2.3, v2.4 의 3종류가 있으며 2.2 는 거의 사용되지 않고 2.3, 2.4 버전 중심으로 사용되고 있습니다. 

<font color="red" style="font-weight:bold;background-color:#eeeeee;font-size:15px;">해당 강좌는 ID3v2.3 버전을 기준으로 작성합니다.</font>

### ID3v2 전체 구조


![img](images/2.jpg)

ID3v2.2 와 ID3v2.3 은 일반적으로 파일의 맨 앞부분에 삽입됩니다.(ID3v2.4 버전부터는 선택적으로 파일의 뒷부분에 삽입이 가능합니다.) ID3v2 정보가 있는 MP3 파일을 [hex 뷰어](https://mh-nexus.de/en/hxd/) 같은 프로그램으로 열어보면 파일의 맨 첫부분에 **ID3** 라는 글자가 표기된것을 확인 할 수 있으며 우리는 이 데이터를 읽는 방법에 대해 이야기 할 예정입니다.


<table width="100%" border="0" style="border:1px solid #000000;">
    <tr>
        <td style="height:40px;border:1px solid #000000;text-align:center;background-color:#ffffff;">헤더</td>
        <td style="border:1px solid #000000;text-align:center;background-color:#ffffff;">프레임1
            <table width="100%">
                <tr>
                    <td style="text-align:center;">헤더</td>
                    <td style="text-align:center;">필드...</td>
                </tr>
            </table>
        </td>
        <td style="border:1px solid #000000;text-align:center;background-color:#ffffff;">프레임2</td>
        <td style="border:1px solid #000000;text-align:center;background-color:#ffffff;">프레임3</td>
        <td style="border:1px solid #000000;text-align:center;background-color:#ffffff;">프레임4</td>
        <td style="border:1px solid #000000;text-align:center;background-color:#ffffff;">....</td>
        <td style="border:1px solid #000000;text-align:center;background-color:#ffffff;">패딩(옵셔널)</td>
        <td style="border:1px solid #000000;text-align:center;background-color:#ffffff;">풋터(옵셔널)</td>
    </tr>
</table>

직접 MP3 파일을 열어 hex 뷰어로 본 16진수로 표기된 도깨비같은 문자가 뭘 의미하는지 알 수 없으나 ID3v2 의 구조는 위의 표에서 처럼 ID3 의 헤더가 있고 각각의 메터데이터는 각각의 프레임에 저장되어있습니다. 또한 각 프레임은 헤더와 1개 이상의 필드로 구성되어있고 몇개든 존재할 수 있으며 뒤의 패딩과 풋터는 옵셔널 항목으로 있을수도 있고 없을수도 있는 항목들 입니다. 여기서 ID3v2를 분석하기 위해서 가장 중요한 부분은 헤더와 각 프레임을 분석하는 부분입니다.



### ID3v2 헤더

![img](images/4.jpg)

직접 MP3 파일을 열어 ID3v2 태그의 헤더 10바이트(16진수로 A)의 내용을 보면 위의 이미지에서 처럼 ```49 44 33 03 00 00 00 00 75 51``` 로 보입니다. 그럼 이제부터 16진수로 표기된 위 내용이 무엇을 의미하고 어떤 정보가 담겼는지를 한번 확인해 봐야겠습니다.

<table width="100%" border="0" style="border:1px solid #000000;">
    <tr>
        <td width="15%" style="height:45px;text-align:center">항목</td>
        <td width="10%" style="text-align:center">offset</td>
        <td width="10%" style="text-align:center">bytes</td>
        <td width="25%" style="text-align:center">hex</td>
        <td width="40%" style="text-align:center">설명</td>
    </tr>
    <tr>
        <td style="height:35px;text-align:center;">ID3v2 식별자</td>
        <td style="text-align:center;">00~02</td>
        <td style="text-align:center;">3 bytes</td>
        <td style="text-align:center;">0x49, 0x44, 0x33</td>
        <td style="text-align:left;padding-left:10px;">"ID3" 문자열</td>
    </tr>
    <tr>
        <td style="height:35px;text-align:center;">ID3v2 버전</td>
        <td style="text-align:center;">03, 04</td>
        <td style="text-align:center;">2 bytes</td>
        <td style="text-align:center;">0x03, 0x00</td>
        <td style="text-align:left;padding-left:10px;">앞 바이트는 주버전, 뒤 바이트는 리비전 번호 </td>
    </tr>
    <tr>
        <td style="height:35px;text-align:center;">ID3v2 플래그</td>
        <td style="text-align:center;">05</td>
        <td style="text-align:center;">1 bytes</td>
        <td style="text-align:center;font-size:15px;">%abc00000</td>
        <td style="text-align:left;padding-left:10px;">a비트: Unsynchronisation<br>b비트: Extended header<br>c비트: Experimental indicator<br>사용하지 않을시엔 0x00 으로 설정</td>
    </tr>
    <tr>
        <td style="height:35px;text-align:center;">ID3v2 크기</td>
        <td style="text-align:center;">06~09</td>
        <td style="text-align:center;">4 bytes</td>
        <td style="text-align:center;">0x00, 0x00, 0x75, 0x51</td>
        <td style="text-align:left;padding-left:10px;">헤더를 제외한 ID3v2 태그 전체 크기(최대 256메가)<br>
        공식사이트에 4 * %0xxxxxxx 로 표기(바이트당 7비트 사용)</td>
    </tr>
</table>

공식사이트에 나온 내용을 정리하자면 ID3v2 헤더는 위의 표와 같은 구조를 갖고 있습니다. 일단 처음 보는 입장에서는 무슨 얘긴지 알기 힘드니 이제 ID3v2 버전으로 기록된 MP3 파일을 실제 열어보면서 이야기를 하고자 합니다. 


In [1]:
from io import BytesIO

filename = "bensound-newdawn.mp3"

mp3 = open(filename, "rb")

# ID3v2 헤더 크기는 10바이트
header_size = 10
header_data = mp3.read(header_size)
id3_header = BytesIO(header_data)

ID3_TAG = id3_header.read(3)
ID3_VERSION = id3_header.read(2)
ID3_FLAGS = id3_header.read(1)
ID3_SIZE = id3_header.read(4)

print(ID3_TAG, ID3_VERSION, ID3_FLAGS, ID3_SIZE)

b'ID3' b'\x03\x00' b'\x00' b'\x00\x00uQ'


위 코드는 ID3v2 의 헤더정보(10바이트) 를 바이트 상태로 출력하는 샘플 코드 입니다. 위에서 본 hex 뷰어의 결과는 16진수로 표기된 것이고 위의 코드에서는 바이트 자체를 표기한것이기 때문에 약간 다릅니다. hex 뷰어에서처럼 똑같이 출력하려면 이 바이트 데이터를 다시 16진수로 변환해야 합니다. 일단 위의 코드를 실행해보면 ```b'ID3' b'\x03\x00' b'\x00' b'\x00\x00uQ'``` 이런 결과를 얻을 수 있습니다. 위의 설명대로 첫 3바이트는 ID3 문자열이 나오고 그 뒤로는 태그 버전이 0x03, 0x00 으로 출력됩니다. 앞 1바이트의 0x03 은 주버전으로 이는 해당 태그의 버전이 ID3v2.3.0 이란것을 알 수 있습니다. 그 뒤 1바이트는 Flags 값이고 마지막 4바이트는 해당 MP3 의 ID3v2 의 사이즈 정보 입니다.


### 사이즈 구하기

ID3v2 태그를 읽는 기능에서는 크게 중요하지 않으나 만약 ID3v2 태그를 기록하는 프로그램을 만든다면 사이즈 정보가 제대로 저장되어야 하기 때문에 여기서 간단하게라도 짚고 넘어갈 필요가 있는 부분입니다. 


***"ID3v2 태그 크기는 4 바이트로 인코딩되며 최상위 비트 (비트 7)는 모든 바이트에서 0으로 설정되어 총 28 비트가됩니다. "***

공식문서에 있는 내용을 그대로 번역하면 위의 설명처럼 나오는데 일단 중요한 부분은<font color="red" style="background-color:#eeeeee;font-weight:bold">ID3v2 에서 사이즈 정보는 28비트로 처리</font>가 된다는 사실입니다. 이 말이 중요한 부분은 원래 ```1바이트 = 8비트``` 이기 때문에 4바이트의 사이즈 정보는 4 * 8 = 32비트 일테지만 공식문서에 나와있듯이 ID3v2 에서는 28비트로 처리한다고 표기되어있기 때문에 32비트로 처리하면 전혀 다른 사이즈 값이 나오게 되니 주의해야 합니다. 어쨌든 위의 코드에서 사이즈 값인 ```b'\x00\x00uQ'``` 을 실제 사이즈 데이터로 변환하는 과정을 살펴보도록 하겠습니다.

- ```b'\x00\x00uQ'``` 값을 hex() 함수를 이용하여 16진수 값으로 변환하면 ```00007551``` 입니다. 이 값을 00, 00, 75, 51 처럼 4바이트로 다시 분리해야 합니다. 그리고 각 바이트 값을 2진수로 변환합니다. ```0x00``` 은 값이 없으니 2진수로 변환하면 ```00000000``` 입니다. 16진수 ```0x75``` 를 2진수로 변경하면 ```1110101``` 이고 ```0x51``` 은 ```1010001``` 입니다.

- 따라서 16진수 ```00, 00, 75, 51``` 을 2진수로 변환하면 ```00000000(8), 00000000(8), 01110101(8), 01010001(8)``` 입니다. 그러나 ID3v2 공식문서에 나온대로 사이즈 정보는 28비트를 사용한다고 했으니 각 바이트에서 맨 왼쪽 1비트씩을 제거하여 ```0000000(7), 0000000(7), 1110101(7), 1010001(7)``` 처럼 만들어 한줄로 작성합니다.

- ```0000000000000011101011010001(28)``` 이렇게 28비트를 한줄로 작성된 값을 10진수로 변경하면 ```15057``` 이란 값이 나오고 해당 MP3 파일에는 15057 바이트의 메타 정보가 있다고 볼 수 있습니다.

- 여기서 작성된 사이즈 정보에는 <font color="red">ID3v2 의 헤더크기인 10바이트가 빠진 값</font>이기 때문에 만약 ID3v2 태그를 저장할때는 최종 사이즈 + 10바이트를 해야만 되고 위의 경우에서 파일의 0 위치부터 15067 바이트가 헤더를 포함한 ID3v2 태그의 전체 크기로 볼 수 있습니다.

![img](images/3.jpg)

위의 이미지에서 처럼 hex 뷰어로 실제 mp3 파일을 직접 열어봤을때 ```b'\x00\x00uQ'``` 값으로 ID3v2 사이즈를 구한 값(10진수 15057)에 헤더를 포함한(10바이트) 최종 15067 바이트(16진수로 3ADB) 크기 만큼이 위 MP3 파일에서의 ID3v2 메타데이터가 저장된 공간입니다.

In [2]:
str_hex = ID3_SIZE.hex()
print("최초 16진수 값:", str_hex)


slice_hex = []
for i in range(0, len(str_hex), 2):
    slice_hex.append(str_hex[i:i+2])

# 위의 for 문을 한줄로 작성하면 아래와 같음
# slice_hex = [str_hex[i:i+2] for i in range(0, len(str_hex), 2)]
print("각바이트 16진수값:", slice_hex)

results = ""
for h in slice_hex:
    tmp_2bin = "{:07b}".format(int(h, 16))
    print("{} => {}".format(h, tmp_2bin))
    results += tmp_2bin

print("최종 2진수:", results)

size = int(results, 2)
print("실제 사이즈:", size)

최초 16진수 값: 00007551
각바이트 16진수값: ['00', '00', '75', '51']
00 => 0000000
00 => 0000000
75 => 1110101
51 => 1010001
최종 2진수: 0000000000000011101011010001
실제 사이즈: 15057


위의 코드는 ID3v2 헤더에 표기된 사이즈 값을 토대로 실제 사이즈 데이터로 변환하는 코드를 아주 직접적이고 쉬운 버전으로 작성한 예제 입니다. 이제 코드의 각 부분을 좀 더 살펴보겠습니다.

<br><pre style="background-color:#eeeeee;margin:0px;padding:10px;">
str_hex = ID3_SIZE.hex()
</pre>
먼저 앞서 구한 ID3_SIZE 변수에 담긴 ``` b'\x00\x00uQ'``` 값을 16진수 값 ```00007551``` 으로 변환하여 str_hex 변수에 저장합니다.

<br><pre style="background-color:#eeeeee;margin:0px;padding:10px;">
slice_hex = []
for i in range(0, len(str_hex), 2):
    slice_hex.append(str_hex[i:i+2])
</pre>

```str_hex``` 변수에 담긴 ```00007551``` 값을 2자리씩 잘라서 ```00, 00, 75, 51``` 로 나누어 ```slice_hex``` 변수에 저장합니다. 이렇게 4개로 나눠진 16진수 값은 각 4바이트에 해당하는 값을 의미합니다.



<br><pre style="background-color:#eeeeee;margin:0px;padding:10px;">
results = ""
for h in slice_hex:
    tmp_2bin = "{:07b}".format(int(h, 16))
    print("{} => {}".format(h, tmp_2bin))
    results += tmp_2bin
</pre>

4개로 나뉘어 담긴 ```slice_hex``` 리스트형 변수를 for 문으로 반복하여 각각의 값을 7자리 2진수로 포맷팅합니다. for문 안의 ```h``` 변수 에는 ```00, 00, 75, 51``` 각각의 값이 반복되어 들어갈테고 이 ```h``` 값을 ```int(h, 16)``` 에 의해 10진수화 시킨 후 ```format```함수에 의해 문자열 값을 설정하게 됩니다. 이때 포맷팅의 ```"{:07b}"``` 에서 b 는 2진수를 의미하고 07 은 0으로 채운 7자리로 셋팅하라는 의미입니다. 이렇게 각 16진수값을 7자리 2진수로 변환하여 ```0000000, 0000000, 1110101, 1010001``` 을 구할 수 있습니다. 이 값을 모두 ```results``` 변수에 누적시키게 되면 모든 값이 한줄로 ```0000000000000011101011010001``` 이렇게 저장 됩니다. 


<br><pre style="background-color:#eeeeee;margin:0px;padding:10px;">
size = int(results, 2)
</pre>
이렇게 최종적으로 모두 한줄로 저장된 ```results``` 의 값 ```0000000000000011101011010001```를 다시 10진수로 변환하면 실제 ID3v2 에서 사용되는 실제 바이트수 ```15057``` 를 구할 수 있습니다.