
TAGS = {
    0x010E: ("Image Description", "이미지 설명", {}),
    0x010F: ("Make", "카메라 제조사", {}),
    0x0110: ("Model", "카메라 모델", {}),
    0x0112: ("Orientation", "사진 촬영시 카메라의 방향", {1:"upper-left", 3:"lower-right", 6:"upper-right", 8:"lower-left", 9:"undefined"}),
    0x011A: ("XResolution", "X축 디스플레이/인쇄 해상도", {}),
    0x011B: ("YResolution", "Y축 디스플레이/인쇄 해상도", {}),
    0x0128: ("ResolutionUnit", "위의 디스플레이/인쇄 해상도의 단위", {1:"단위없음", 2:"인치", 3:"센티미터"}),
    0x0131: ("Software", "펌웨어 버전 번호", {}),
    0x0132: ("DateTime", "YYYY:MM:DD HH:MM:SS", {}),
    0x013E: ("WhitePoint", "이미지의 흰색점의 색도 정의.", {}),
    0x013F: ("PrimaryChromaticities", "이미지 원색의 색도 정의", {}),
    0x0211: ("YCbCrCoefficients", "이미지 형식이 YCbCr 인 경우 RGB 형으로 변환하는 상수 표시.", {}),
    0x0213: ("YCbCrPositioning", "이미지 형식이 YCbCr 이고 서브샘플링을 사용하는 경우", {1:"픽셀어레이 중심", 2:"데이텀 포인트 를 의미"}),
    0x0214: ("ReferenceBlackWhite", "흑점/백점의 기준값을 표시", {}),
    0x8298: ("Copyright", "저작권 정보 표시", {}),
    0x8769: ("ExifOffset", "Exif Sub IFD의 오프셋", {}),
    0x8825: ("GPSInfo", "GPS 정보 IFD 오프셋", {}),

    0x0100: ("ImageWidth", "썸네일 이미지 가로 크기", {}), 
    0x0101: ("ImageHeight", "썸네일 이미지 세로 크기", {}), 
    0x0103: ("Compression", "압축", {1:"압축안함", 6:"JPEG압축"}), 
    0x0112: ("Orientation", "방향", {1:"Horizontal", 2:"Mirror Horizontal", 3:"Rotate 180", 4:"Mirror vertical", 5:"Mirror horizontal and rotate 270 CW", 6:"Rotate 90 CW", 7:"Mirror horizontal and rotate 90 CW", 8:"Rotate 270 CW"}), 
    0x0201: ("JpegIFOffset", "JPEG 오프셋", {}), 
    0x0202: ("JpegIFByteCount", "JPEG 바이트 수", {}), 

    0x829A: ("ExposureTime", "노출 시간", {}),
    0x829D: ("FNumber", "촬영시 조리개 값", {}),
    0x8822: ("ExposureProgram", "촬영시 카메라의 노출 모드", {1:"메뉴얼", 2:"프로그램", 3:"조리개우선", 4:"셔터우선", 5:"크리에이티브모드", 6:"프로그램액션", 7:"인물모드", 8:"풍경모드"}),
    0x8827: ("ISOSpeedRatings", "ISO 감도", {}),
    0x9000: ("ExifVersion", "4바이트 문자의 Exif 버전", {}),
    0x9003: ("DateTimeOriginal", "이미지 원본 촬영 시간", {}),
    0x9004: ("DateTimeDigitized", "이미지가 디지털로 기록된 시간. 일반적으로 DateTimeOriginal 과 동일", {}),
    0x9101: ("ComponentConfiguration", "ComponentConfiguration", {}),
    0x9102: ("CompressedBitsPerPixel", "JPEG 평균 압축률", {}),
    0x9201: ("ShutterSpeedValue",  "셔터속도", {}),
    0x9202: ("ApertureValue", "이미지 촬영시 실제 렌즈 조리개값", {}),
    0x9203: ("BrightnessValue", "촬영한 피사체의 밝기", {}),
    0x9204: ("ExposureBiasValue", "촬영시 노출값", {}),
    0x9205: ("MaxApertureValue", "촬영시 사용된 렌즈의 최대 조리개 값", {}),
    0x9206: ("SubjectDistance", "초점 거리", {}),
    0x9207: ("MeteringMode", "노출 측광방식", {1:"평균측광", 2:"중앙평균측광", 3:"스팟측광", 4:"멀티스팟", 5:"다중측광"}),
    0x9208: ("LightSource", "화이트밸런스 광원설정", {0:"자동", 1:"일광", 2:"형광등", 3:"텅스텐", 10:"플래시"}),
    0x9209: ("Flash", "플래시 사용여부", {1:"플래시사용", 0:"플래시사용안함"}),
    0x920A: ("FocalLength", "촬영시 렌즈의 초점거리", {}),
    0x927C: ("MakerNote", "제조사 내부 데이터영역", {}),
    0x9286: ("UserComment", "사용자 코멘트", {}),
    0xA000: ("FlashPixVersion", "플래시픽스 버전", {}),
    0xA001: ("ColorSpace", "ColorSpace", {}),
    0xA002: ("ExifImageWidth", "이미지 넓이", {}),
    0xa003: ("ExifImageHeight", "이미지 높이", {}),
    0xA004: ("RelatedSoundFile", "촬영시 오디오 데이터를 녹음한 경우 오디오 데이터의 이름 표시", {}),
    0xA005: ("ExifInteroperabilityOffset", "ExifInteroperabilityOffset", {}),
    0xA20E: ("FocalPlaneXResolution", "CCD의 가로 픽셀 밀도", {}),
    0xA20F: ("FocalPlaneYResolution", "CCD의 세로 픽셀 밀도", {}),
    0xA210: ("FocalPlaneResolutionUnit", "CCD의 픽셀 밀도의 단위", {1:"단위없음", 2:"인치", 3:"센티미터"}),
    0xA217: ("SensingMethod", "이미지 센서 유닛종류", {}),
    0xA300: ("FileSource", "'3' 고정됩니다.", {}),
    0xA301: ("SceneType", "'1' 고정됩니다.", {}),

    0x9290: ("SubSecTime", "날짜 수정에 대한 분수 초", {}),
    0x9291: ("SubSecTimeOriginal", "DateTimeOriginal에 대한 분수 초", {}),
    0x9292: ("SubSecTimeDigitized", "CreateDate에 대한 분수 초", {}),
    0xA401: ("CustomRendered", "사용자 지정 렌더링", {0:"노말", 1:"커스텀"}),
    0xA402: ("ExposureMode", "노출모드", {0:"오토", 1:"메뉴얼", 2:"자동 브래킷"}),
    0xA403: ("WhiteBalance", "화이트밸런스", {0:"오토", 1:"메뉴얼"}),
    0xA404: ("DigitalZoomRatio", "디지털줌 비율", {}),
    0xA405: ("FocalLengthIn35mmFormat", "35mm필름 형식", {}),
    0xA406: ("SceneCaptureType", "촬영모드", {0:"스탠다드", 1:"풍경", 2:"인물", 3:"나이트", 4:"기타"}),
    0xA407: ("GainControl", "게인 컨트롤", {0:"None", 1:"Low gain up", 2:"High gain up", 3:"Low gain down", 4:"High gain down"}),
    0xA408: ("Contrast", "대비", {0:"Normal", 1:"Low", 2:"High"}),
    0xA409: ("Saturation", "채도", {0:"Normal", 1:"Low", 2:"High"}),
    0xA40A: ("Sharpness", "선명도", {0:"Normal", 1:"Soft", 2:"Hard"}),
    0xA420: ("ImageUniqueID", "이미지 고유넘버", {}),

    0x0000: ("GPSVersionID", "GPS 태그 버전", {}),
    0x0001: ("GPSLatitudeRef", "북위 또는 남위", {}),
    0x0002: ("GPSLatitude", "위도", {}),
    0x0003: ("GPSLongitudeRef", "동쪽 또는 서쪽 경도", {}),
    0x0004: ("GPSLongitude", "경도", {}),
    0x0005: ("GPSAltitudeRef", "고도 참조", {}),
    0x0006: ("GPSAltitude", "고도", {}),
    0x001D: ("GPSDateStamp", "GPS 날짜", {}),
    0x0007: ("GPSTimeStamp", "GPS 시간(원자시계)", {}),
    0x001B: ("GPSProcessingMethod", "GPS 처리 방식 이름", {}),
}

FORMAT_TYPES = (
    (0, ""),
    (1, "B", "unsigned byte"),
    (1, "c", "ascii"),
    (2, "H", "unsigned short"),
    (4, "L", "unsigned long"),
    (8, "Q", "unsigned rational"),
    (1, "b", "signed byte"),
    (1, "", "undefined"),
    (2, "h", "signed short"),
    (4, "l", "signed long"),
    (8, "q", "signed rational"),
    (4, "f", "single float"),
    (8, "d", "double float")
)
